sudo: false
before_install:
  - cat fallback-renderers.ttl
branches:
  only: 
    - gh-pages
    - /.*/ 
deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis_publish
    on:
      tags: true